### ISSUE TITLE
Backdoor in this autominer

### ISSUE THREAD

**Issue by Kanorto** [Poryaei/NotCoin-Clicker#10]
![image](https://github.com/Poryaei/NotCoin-Clicker/assets/77388225/0befecb7-215d-45a3-84e3-f842ef01f989)
![image](https://github.com/Poryaei/NotCoin-Clicker/assets/77388225/4eb6577d-d694-4f02-9442-fa1b740d19a0)
Подскажите пожалуйста, как понимать эти упоминания статического ID пользователя в качестве администратора? Зачем это сделано? Это файл clicker.py, строки указаны на скриншотах.

**Comment by Poryaei** [comment]
if you think for a bit, you'll realize that ID 6583452530 is the user_id of the https://t.me/notcoin_bot!!!!

**Comment by Kanorto** [comment]
> if you think for a bit, you'll realize that ID 6583452530 is the user_id of the https://t.me/notcoin_bot!!!!

oh, sorry;(

**Comment by Poryaei** [comment]
> > if you think for a bit, you'll realize that ID 6583452530 is the user_id of the https://t.me/notcoin_bot!!!!
> 
> oh, sorry;(

No problem ❤️
