### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by dedanab** [Poryaei/NotCoin-Clicker#11]
It would be nice to add multithreading. Yes, unfortunately, you will have to give up managing via Telegram for each account, but purely in theory, you can manage all accounts through linking to one Telegram bot.
Regarding multithreading. This will be a very convenient feature because now there are few places like this

**Comment by Poryaei** [comment]
Sure, I'm working on it and it's almost 70% complete! I'll release it soon. Thank you for your suggestion.

**Comment by dedanab** [comment]
> Sure, I'm working on it and it's almost 70% complete! I'll release it soon. Thank you for your suggestion.

Great. I'm really looking forward to it :)
