### ISSUE TITLE
where, to which bot should you give these commands?

### ISSUE THREAD

**Issue by dgzimin** [Poryaei/NotCoin-Clicker#12]
```
/help to view help
/click to enable/disable collection
/balance to check NotCoin balance
/speed 1-10 to set collection speed (1-10)
/stop to Stop bot
```
and where, to which bot should you give these commands?

**Comment by Poryaei** [comment]
Hi your client account in telegram

**Comment by dgzimin** [comment]
> Hi your client account in telegram

um, sorry for being stupid, in what chat?

**Comment by dgzimin** [comment]
with your numbers and logged in and chatid from this number in the config.

**Comment by dgzimin** [comment]
figured it out, write to Favorites. Thx
