### ISSUE TITLE
Not Working on linux

### ISSUE THREAD

**Issue by BarbieGosling** [Poryaei/NotCoin-Clicker#13]
File "clicker.py", line 264
    match current_buff['taskId']:
          ^

**Comment by Poryaei** [comment]
Use python 3.10 >

**Comment by BarbieGosling** [comment]
I use last python version

чт, 18 янв. 2024 г., 21:29 Abolfazl ***@***.***>:

**Comment by Poryaei** [comment]
If your Python version is 3.10 or higher, you won't have any issues.
If you want to make sure about your Python version, use
```python -v```
