### ISSUE TITLE
Mining Error

### ISSUE THREAD

**Issue by BarbieGosling** [Poryaei/NotCoin-Clicker#15]
Mining Error:  Expecting value: line 1 column 1 (char 0)

**Comment by Poryaei** [comment]
Are you using the latest version? Can you please send me a screenshot of the terminal?

**Comment by BarbieGosling** [comment]
I'm use latest version. 
![изображение](https://github.com/Poryaei/NotCoin-Clicker/assets/157055409/e52d7027-234b-4644-86e6-7ccb0f9870f8)

**Comment by BarbieGosling** [comment]
Requirement already satisfied: PySocks in /usr/local/lib/python3.10/dist-packages (1.7.1)
S

**Comment by Poryaei** [comment]
I'll fix the issue in the next update. If you want, you can run the robot without using a proxy, but it requires a clean and not blocked IP by CloudFlare!  
In the clicker.py file, change line 191 from
self.useProxy = True
to
self.useProxy = False

**Comment by BarbieGosling** [comment]
this error occurs due to an uncollected reward from the robot (which gives out coins when you are not playing), you need to collect the reward and then your bot will work.

**Comment by Poryaei** [comment]
> this error occurs due to an uncollected reward from the robot (which gives out coins when you are not playing), you need to collect the reward and then your bot will work.

I don't really think this way! But I'll look into it.
