### ISSUE TITLE
Syntax error on raspbian os

### ISSUE THREAD

**Issue by Fess23** [Poryaei/NotCoin-Clicker#17]
OS: Raspbian os
Device: Rasberry pi 3b+
PY version: Python 3.9.2

When i starting the script i will get this error:
`  File "/home/Fess/notcoin-clicker/NotCoin-Clicker/clicker.py", line 297
    match current_buff['taskId']:
          ^
SyntaxError: invalid syntax
`

**Comment by Poryaei** [comment]
Try install python 3.10 >

**Comment by Poryaei** [comment]
If you can't install Python version 3.10 or higher, you need to change the way the get_free_buffs_data function is written in the clicker class instead of using match case, we should use if.

**Comment by Fess23** [comment]
Thank for your review, after 5 hours of installing, i finally done it by installing 3.10 version of python)
