### ISSUE TITLE
'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by kadsystems** [Poryaei/NotCoin-Clicker#18]
After installing and starting got an error Mining Error:  'NoneType' object has no attribute 'text'

As I understood problem in 251-252 strings. I am using the last version, just installed. 

Logged in with phone and code cause bot http api token did not work. 

![image](https://github.com/Poryaei/NotCoin-Clicker/assets/27851002/4a230ab9-0bac-4b6c-987b-ac9c1ea591e9)

**Comment by kadsystems** [comment]
I greatly appreciated your efforts. Good job! Thank you!

**Comment by slipizz** [comment]
Bro! How did you solve this problem??

**Comment by kadsystems** [comment]
> Bro! How did you solve this problem??

I did not, unfortunately

**Comment by Poryaei** [comment]
> By the way, I greatly appreciated your efforts with this code. Good job! Thank you! Looking forward for your reply about the issue

Hello, thank you so much for your kind words. Please try the new version of the code, and if the issue has not been resolved, please let me know.

**Comment by slipizz** [comment]
Now he writes another error
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
[!] No valid proxy!
[!] No valid proxy!
Mining Error:  'bool' object has no attribute 'text'
False

**Comment by Poryaei** [comment]
> Now he writes another error [!] Mining 20 coins field! [~] Generating New Auth [+] Lets mine ... [!] No valid proxy! [!] No valid proxy! Mining Error: 'bool' object has no attribute 'text' False

This error is due to not finding a valid proxy!
In the file clicker.py, change line 112 from
response = session_func(*args, proxies=proxy, timeout=10, **kwargs)
to
response = session_func(*args, proxies=proxy, timeout=20, **kwargs)

Also, test it once to see if you've installed its prerequisites:

```python -m pip install -r requirements.txt```

**Comment by slipizz** [comment]
All the same errors, everything is installed, I changed the timeout to 20, it does not help.

**Comment by Poryaei** [comment]
To bypass Cloudflare, there are two options! Either use a clean IP or use a proxy. Once, run the code without using a proxy on line 187:
Change
self.useProxy = True
to
self.useProxy = False
If this doesn't solve the problem, I have no idea how to bypass the current Cloudflare restrictions and will have to spend more time to find a new way!

**Comment by slipizz** [comment]
The problem was with the proxy. Thanks!

**Comment by kadsystems** [comment]
> self.useProxy = False

thank you, everything is working fine. What is the problem with proxy, why can not find proxy? Are there any other ways to use proxy?

**Comment by Poryaei** [comment]
> > self.useProxy = False
> 
> thank you, everything is working fine. What is the problem with proxy, why can not find proxy? Are there any other ways to use proxy?

now if you want to update the script once again and test it with a proxy , I don't think there should be any problem! (Some servers couldn't fetch the proxies from the website's API, so I connected it to my website for it to fetch the proxies from there.)

**Comment by kadsystems** [comment]
> now if you want to update the script once again and test it with a proxy , I don't think there should be any problem! (Some servers couldn't fetch the proxies from the website's API, so I connected it to my website for it to fetch the proxies from there.)

Updated, everything working fine now. Can I use a bot id without phone number and code? When I try to use a bot token I got error, but possibly I use wrong data. Should I use the token I received when creating the bot?

![image](https://github.com/Poryaei/NotCoin-Clicker/assets/27851002/ad061d3e-53bf-4338-a74f-dae2a7610614)

**Comment by Poryaei** [comment]
It's impossible!  Robots can't access each other. That means you must definitely use a mobile number to log in.

**Comment by Poryaei** [comment]
if there is no problem and it is resolved, let's close the issues

**Comment by kadsystems** [comment]
> It's impossible! Robots can't access each other. That means you must definitely use a mobile number to log in.

Understood, but for some reason there is writing "(or bot token)" so I am wondering how this is supposed to work?
