### ISSUE TITLE
The formula for calculating the number of coins

### ISSUE THREAD

**Issue by BrasD99** [Poryaei/NotCoin-Clicker#24]
Hi!
I have another proposal to improve the project. I studied the JS scripts from their application and got the formula by which the maximum number of coins that the server accepts (/clicker/core/click) during the request is calculated.

I suggest calculating this value in startMin:
```
getData = self.sendCoins(_sc, _sh)
data = getData["data"][0]
...
_sc = int(159 * data["multipleClicks"] * random.uniform(0.8, 1.0))
```

I use random so that the number of coins varies slightly with each request.

**Comment by shamhi** [comment]
Use my bot https://github.com/shamhi/NotCoinBot

**Comment by Poryaei** [comment]
Hello, thank you for the code you sent!
I prefer not to do this. Naturally, there is a possibility of the bot being identified with this action
But anyway, thank you for your suggestion.
