### ISSUE TITLE
The method you tried to invoke cannot be executed as a bot (caused by RequestWebViewRequest)

### ISSUE THREAD

**Issue by JohnLi92** [Poryaei/NotCoin-Clicker#3]
**The method you tried to invoke cannot be executed as a bot (caused by RequestWebViewRequest)**

```
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by RequestWebViewRequest)
[1]    80861 segmentation fault  python clicker.py
```

1. I create bot use [@BotFather](https://t.me/BotFather)
2. use https://my.telegram.org/apps create the app
3. when I launch 'python clicker.py', it show the error.

**Comment by Poryaei** [comment]
Clear .session files and run client on your account (use Phone number )

**Comment by JohnLi92** [comment]
Thanks, run success.

**Comment by tawanaproxy** [comment]
i want run in bot what should ido i get thie errore
