### ISSUE TITLE
Activating F Energy Problem

### ISSUE THREAD

**Issue by shadow-mafi** [Poryaei/NotCoin-Clicker#35]
Activing F Energy!
Mining Error:    unhashable type: 'list'
Sleeping For 10MIN

it activates the energy but doesnt mine and sleeps 

edit:

guys i solved the problem in line 266 change this 
`return ['ok'] in r.json()`
to this 
`return 'ok' in r.json()`

**Comment by Poryaei** [comment]
My bad
Thanks.
