### ISSUE TITLE
Full Energy Bug

### ISSUE THREAD

**Issue by shadow-mafi** [Poryaei/NotCoin-Clicker#36]
Hi Thank You For Your Hard Work 

Scripts Doesn't Check If There Is Full Energy Available Just Activates It Even There Is Not Any Full Energy Boost And Starts Mining And Doesn't Wait For 10 Min To Regain Energy.

**Comment by Poryaei** [comment]
You can use the code below until I find time to update the script. 

https://github.com/Poryaei/NotCoin-Clicker/issues/22

Thanks to @BrasD99 🙏
