### ISSUE TITLE
Proxy detection 

### ISSUE THREAD

**Issue by iamrustamov** [Poryaei/NotCoin-Clicker#37]
After a few hours of program execution, there are issues with proxy detection. The following log is outputted when running the program:

INFO:root:[+] Lets mine ...
INFO:root:[-] Updating webview URL ...
INFO:root:[+] WebView URL UPDATED!
INFO:root:[-] Updating webview URL ...
INFO:root:[+] WebView URL UPDATED!
WARNING:root:[!] No valid proxy!
WARNING:root:[-] Try again ...
INFO:root:[-] Updating webview URL ...
INFO:root:[+] WebView URL UPDATED!
WARNING:root:[!] No valid proxy!
WARNING:root:[-] Try again ...
INFO:root:[-] Updating webview URL ...
INFO:root:[+] WebView URL UPDATED!
WARNING:root:[!] No valid proxy!
WARNING:root:[-] Try again ...

OS: Ubuntu 22
Server location: USA
Python: 3.10 in docker

**Comment by Poryaei** [comment]
The bot cannot find a working proxy! You can turn off the use of proxies, but you need a clean IP (meaning Cloudflare hasn't banned it).

https://github.com/Poryaei/NotCoin-Clicker/issues/18#issuecomment-1913609679
