### ISSUE TITLE
how this

### ISSUE THREAD

**Issue by AwalAditya** [Poryaei/NotCoin-Clicker#41]
eror when run python clicker.py

![Uploading IMG_2018.png…]()

**Comment by Poryaei** [comment]
Bad img buddy

**Comment by AwalAditya** [comment]
> Bad img buddy

wait
![IMG_2018](https://github.com/Poryaei/NotCoin-Clicker/assets/26605327/10b59a8a-ec89-4f1b-8860-9e078cf87849)

**Comment by Poryaei** [comment]
Use python 3.10

**Comment by AwalAditya** [comment]
> Use python 3.10

wait, repairing my python

**Comment by AwalAditya** [comment]
> Use python 3.10

what specific version 3.10.xx i use 3.10.0 still get eror line 2

**Comment by AwalAditya** [comment]
> > Use python 3.10
> 
> what specific version 3.10.xx i use 3.10.0 still get eror line 2

3.10.14 getting same eror, no module named 'js2py'

**Comment by AwalAditya** [comment]
> Use python 3.10

done, im sorry, my bad, thanks for bot ❤️❤️❤️
