### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by boyitnew** [Poryaei/NotCoin-Clicker#42]
I have completed all the steps and I have also run the project. However, I couldn't figure out how to use the WebViewResultUrl in the output, and also, what is the ID of its bot?

**Comment by Poryaei** [comment]
Just send /help to your clicker

**Comment by boyitnew** [comment]
Alright, it's done, thank you. Just one question, why when I type /balance, the balance is different from what I have in my profile? Why aren't the coins being added to my account?

**Comment by boyitnew** [comment]
![2024-03-26_140418](https://github.com/Poryaei/NotCoin-Clicker/assets/100024819/2b70d6ee-3be1-43fa-a5d0-dcef2c42f6e4)

**Comment by Poryaei** [comment]
@boyitnew The robot may update the inventory late due to cache memory (probably).
