### ISSUE TITLE
Some stuff

### ISSUE THREAD

**Issue by nichind** [Poryaei/NotCoin-Clicker#8]
unused import os
https://github.com/Poryaei/NotCoin-Clicker/blob/08f0bb10b31d6b5e0d3503fa74864d1f04fe9a9f/clicker.py#L4

And you might want to change user id int to `admin` variable here
https://github.com/Poryaei/NotCoin-Clicker/blob/08f0bb10b31d6b5e0d3503fa74864d1f04fe9a9f/clicker.py#L424

Also, why use requests & sync code for "clicker"? Writing your code in async and using aiohttp over requests is far better.

**Comment by Poryaei** [comment]
Thank you for your attention

For the second issue, the user_id should remain as is because it is the bot's ID used to retrieve the balance.

As for the third issue, I will consider using async and aiohttp over requests for "clicker" in the future. Thank you for the suggestion.

**Comment by nichind** [comment]
Also, PEP-8 is very usable, you should consider learning it, its not that hard. And if you use VSCode or Pycharm its even easier with plugins

**Comment by nichind** [comment]
> Also, PEP-8 is very usable, you should consider learning it, its not that hard. And if you use VSCode or Pycharm its even easier with plugins

Like, it's really unnecessary to do that....
https://github.com/Poryaei/NotCoin-Clicker/blob/08f0bb10b31d6b5e0d3503fa74864d1f04fe9a9f/clicker.py#L37
https://github.com/Poryaei/NotCoin-Clicker/blob/08f0bb10b31d6b5e0d3503fa74864d1f04fe9a9f/clicker.py#L16

**Comment by Poryaei** [comment]
> Also, PEP-8 is very usable, you should consider learning it, its not that hard. And if you use VSCode or Pycharm its even easier with plugins

I really appreciate your guidance. I'm already familiar with PEP-8
If you have any more suggestions or guidance, I'd be happy to hear them.

**Comment by Poryaei** [comment]
> > Also, PEP-8 is very usable, you should consider learning it, its not that hard. And if you use VSCode or Pycharm its even easier with plugins
> 
> Like, it's really unnecessary to do that....
> 
> https://github.com/Poryaei/NotCoin-Clicker/blob/08f0bb10b31d6b5e0d3503fa74864d1f04fe9a9f/clicker.py#L37
> 
> 
> https://github.com/Poryaei/NotCoin-Clicker/blob/08f0bb10b31d6b5e0d3503fa74864d1f04fe9a9f/clicker.py#L16

I know it's not necessary, but it's just a habit that I've been separating sections with comments while coding. It actually makes it easier for me to work with.
