### ISSUE TITLE
Coins failing to add

### ISSUE THREAD

**Issue by Hiradpi** [Poryaei/NotCoin-Clicker#9]
`False                                         [!] Mining 8 coins field!                            [~] Generating New Auth                              [+] Lets mine ...                                    False                                                [!] Mining 8 coins field!                            [~] Generating New Auth                              [+] Lets mine ...                                    False                                                [!] Mining 8 coins field!                            [~] Generating New Auth                              [+] Lets mine ...                                    False                                                [!] Mining 8 coins field!                            [~] Generating New Auth                              [+] Lets mine ...                                    False`

After turning it on it keeps spamming this 
it worked for a moment but it stopped working after a wile

**Comment by Hiradpi** [comment]
and I have no trouble connecting to tg and tgapi servers

**Comment by Poryaei** [comment]
Hello, try the updated version and let me know if the issue is still not resolved.

**Comment by Akbarjon001** [comment]
> Hello, try the updated version and let me know if the issue is still not resolved.

Hello, with me the same situation and it's still not workin after update

**Comment by Poryaei** [comment]
> > Hello, try the updated version and let me know if the issue is still not resolved.
> 
> Hello, with me the same situation and it's still not working after update

If it's not a problem, could you send me a screenshot of the terminal?

**Comment by cardboard-face** [comment]
I'm also facing the same issue. It's not mining for some reason.
![IMG_20240117_233128_313](https://github.com/Poryaei/NotCoin-Clicker/assets/149292864/c8d47395-dc6a-4797-a50b-745f0bf1f072)

**Comment by Poryaei** [comment]
The problem is that it can't find a suitable proxy to bypass Cloudflare restrictions!
[+] Proxies: None
I'll try to fix this, thank you for sharing.

**Comment by cardboard-face** [comment]
Still, it's showing the same error. Also, now the speed has significantly decreased. Userbot now seems to provide a delayed response for a command.

**Comment by cardboard-face** [comment]
![IMG_20240118_011831_033](https://github.com/Poryaei/NotCoin-Clicker/assets/149292864/ab3a8079-f91b-4616-8b86-003840344397)

**Comment by Poryaei** [comment]
![photo_2024-01-18_19-41-29](https://github.com/Poryaei/NotCoin-Clicker/assets/83473475/36c75937-cbd4-44f7-b32e-c63aced5c42f)

The problem is almost fixed! (For myself and a few friends who tested, there was no issue)

If you don't want to use a proxy, in line 191 of the clicker.py file, change
self.useProxy = True
to
self.useProxy = False!
Keep in mind that in this case, you need a clean IP (not blocked by Cloudflare).

but if there is still a problem, let me know.

**Comment by koo27** [comment]
Changing the `useProxy` to `false` make it works, but just apprently. I don't see any changes in the balance.
```[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
False
```

**Comment by koo27** [comment]
> > Changing the `useProxy` to `false` make it works, but just apparently. I don't see any changes in the balance.
> 
> Please update the clicker.py file again and send me a picture from the terminal so we can see the error.

with proxy = true it just doesn't work.
<img width="366" alt="immagine" src="https://github.com/Poryaei/NotCoin-Clicker/assets/15351634/7bdb71f9-3b6c-461e-822d-1101795c5c5f">

**Comment by koo27** [comment]
with proxy = false now I get this
```
Mining Error:  Expecting value: line 1 column 1 (char 0)
[+] Lets mine ...
Mining Error:  Expecting value: line 1 column 1 (char 0)
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
Mining Error:  Expecting value: line 1 column 1 (char 0)
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
Mining Error:  Expecting value: line 1 column 1 (char 0)
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
Mining Error:  Expecting value: line 1 column 1 (char 0)
False
[!] Mining 20 coins field!
[~] Generating New Auth
[+] Lets mine ...
Mining Error:  Expecting value: line 1 column 1 (char 0)
False
```

**Comment by Poryaei** [comment]
If you just started the robot, wait a bit (at least 1 minute) and then send the commands (during this time, it's finding a proxy and won't respond to your request).

This error is because your IP is restricted by Cloudflare and you need to use a proxy or change your IP in some other way.

**Comment by koo27** [comment]
After waiting for a while, I get this
```
[+] Proxies:   None
Mining Error:  Expecting value: line 1 column 1 (char 0)
```

**Comment by shamhi** [comment]
[use](https://github.com/shamhi/NotCoinBot)

**Comment by Poryaei** [comment]
In the new update, we tried to completely solve the issue! And the bot has been collecting coins for 2 days without any problems!

If you don't want to use a proxy, in line 209 of the file clicker.py, change
self.useProxy = True
to
self.useProxy = False

And if your bot still has problems, try running it on a server to have better internet speed for checking and using the proxy.
